[bigquery]
type = "service_account"
project_id = "air-pollution-explorer"
private_key_id = "ce29095309e213b6fa110ad796eb3ab5d12b96"

# 👇 paste exactly like this, with BEGIN and END on their own lines
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDQSxufjCpLACfY
xzvqZdjiNC7kUyTe/TZi4QoaWammt3Sj0LOP8HIqG4KSIlnfYNQ5cWOxv//ThcLe
vV0tO1yvJK6xGojgRosaDHlhHc7cu+fNA8nrSFLZ7b3Sd4EXF7plvrXFR/18r1OR
OpH08R34p4Lux6eWKaQVG3euGqhQ9nCwHYUoCpy06jXIHevSwL1UPjHSvBU4pCgI
r0PGzpe1z8Zi+n652vjDyRXoN9oTC9aEUGhI7GDyTK+MZfyEXc0Gm2pDk8eC/tOc
38b6bfdGtliuu+dRnkvqSk4UbQh3IoyYlRolz8njpOSX1idocLrB9lXbnFOg8Haj
LM/ZlBaxAgMBAAECggEAA7cAivO+11qX21ZmUP5jBARxPPznS0YnKlP1ewB+tZdP
sGeVpEC3Zd0wEszOXzJaEUeJQyTM+mfy0J0o+cMKxUw5WgrtRllhEWRdOn2ucE0L
oSJAVNQT4jN1b2Or545dR9jtuKiEMq0/0iHCHk+550g5iL+tKKZHzmE7Ml2Nre/x
qmwiWcqFsrauFMtZ10+gFdMLJPUc0ZQh5Xzrm7svxbGGje1VMPvANuHLcJ0alLXR
0p+7rTVEXoWAV5dXu+ihXqw7+qdi+O9mG3AXmtoHzDApe+vQDWWcHA8RxEusvLkN
/mBBDefD2fvSF31v7daXIOg6PUgQ+j6jc16OadbpAQKBgQDz8c/ruwi69TFezYEZ
sWYNAZ0Oyq4UJe0S0b33AZC9llbn4slWybcX9Jh8mfsVbvcz6wJfVfTiLSuXhqRB
FYJ+IdgKOIsPAVgyLHpSz6Eb6ZSnVlORO8sBuNabiDGbvzndD0stLKn3tUcCB9Id
e0KyUaMwjgPEOsRluxgYXjuaUQKBgQDalkQVxgfxnOND8qtt2xeUz17ju+Nqvund
aSOB/v+vg1E+srzdsYM4BiA2EoICaMizSxoPmwq3Nucn6vWIWIvQtQe2lMqsY8hZ
yBt88LrT8TL+iEWXMsYS9nWY6lCW8GOed7/PqZKntZyLlFEdnVeU1RHhskdtyL44
ZttFZO8+YQKBgCjJz+gsd8M66Cxf1CxFmzilgmtMvFqmFMPGyiqY2mi40IMpSlz2
kWSyAyUiYfctfKvzqYvjRXTj9Jv7aU9wl0cbxZG/7pBtux94jGN4UAnovnBUYNix
1LnO/CM5XIIcMUKjIgDFrQ28A8l1IU7Io1hJii2+MScIZHpWFCtO5kxhAoGBAIFi
QJrCxSD2xG8LzP0RmjuzI2+ZX1tn9fXgrevcjGvPRt/d3H08/XbD6X0YJ2xVqba2
1Y43L3iTPvAZ24wBHYFEJnSkTfMMfSLnl520wGGDe7O95bNBkozW5XTF/T3avJyo
NRkuPmiWzzqvZ/Qnlhe6pwL5C96n3DB2cYP54sMBAoGBAI+lFEPUI0EdaAK+Sgzl
a2xdfqQ49RX+XSYm5ElCV7oUT+iM+QMwsavVf8yvSIvwLDWB2Om4qdhsbMPu8uay
T/akabx1Akg7/vprCQAaRSOolT5eTr5CWWZTcS+UJExY20Zmcd+ALgqo37c0vLDz
gQSOEO2OnKfs1RC7xHuTEE8P
-----END PRIVATE KEY-----"""


client_email = "air-pollution-app@air-pollution-explorer.iam.gserviceaccount.com"
client_id = "1166844082535111661"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/air-pollution-app%40air-pollution-explorer.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
